# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Harrison Ding
author: Harrison Ding
email: harrisond2015@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    I am a freshman studying Computer Science in the University of Illinois At Urbana-Champaign.
    I've created this blog as a place to keep track of each of my future projects,
    and possible past and current ones as well. These projects are, by all means, 
    welcome to comments so whoever sees this blog, I do hope you will at least
    send me a message as to what I could improve upon for my project styles.

baseurl: "" # the subpath of your site, e.g. /blog
url: "shorrian.github.io" # the base hostname & protocol for your site
twitter_username: shorrian
github_username: shorrian 
version: 1.1
# Build settings
markdown: kramdown
